//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUẢN_LÝ_THƯ_VIỆN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCGIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DOCGIA()
        {
            this.GIAHANs = new HashSet<GIAHAN>();
            this.MUON_TRA = new HashSet<MUON_TRA>();
        }
    
        public string MADG { get; set; }
        public string HOTEN { get; set; }
        public string DCHI { get; set; }
        public Nullable<System.DateTime> NGSINH { get; set; }
        public string SODT { get; set; }
        public Nullable<System.DateTime> NGDK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIAHAN> GIAHANs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MUON_TRA> MUON_TRA { get; set; }
    }
}
