//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUẢN_LÝ_THƯ_VIỆN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUON_TRA
    {
        public string MADG { get; set; }
        public string MASACH { get; set; }
        public Nullable<int> SL { get; set; }
        public Nullable<System.DateTime> NGMUON { get; set; }
        public Nullable<System.DateTime> NGQDTRA { get; set; }
        public Nullable<System.DateTime> NGTRA { get; set; }
        public Nullable<decimal> PHATQH { get; set; }
    
        public virtual DOCGIA DOCGIA { get; set; }
        public virtual SACH SACH { get; set; }
    }
}
